            # language: es

            Característica: designar una persona a un cargo docente
            actividad central de información de la escuela secundaria

            Esquema del escenario: Designación de persona en cargos NO cubiertos aún en el perído indicado de forma existosa
            Dada la persona con "<DNI>" "<nombre>" y "<apellido>"
            Y que se asigna al cargo con tipo de designación "<tipo>" y "<nombreDesignacion>"
            Y si es espacio curricular asignada a la división <anio> <numero> "<turno>"
            Y se designa por el período "<fechaDesde>" "<fechaHasta>"
            Cuando se presiona el botón guardar en designaciones
            Entonces se espera el siguiente <status> y "<respuesta>"

            Ejemplos:
            | DNI      | nombre      | apellido     | tipo               | nombreDesignacion | anio | numero | turno   | fechaDesde | fechaHasta | status | respuesta                                                                                                                                                   |
            | 10100100 | Alberto     | Lopez        | CARGO              | Vicedirector      | 0    | 0      | null    | 2023-03-01 |            | 200    | Alberto Lopez ha sido designado/a como Vicedirector exitosamente                                                                                            |
            | 20200200 | Susana      | Álvarez      | CARGO              | Preceptor         | 0    | 0      | null    | 2023-03-01 | 2023-12-31 | 200    | Susana Álvarez ha sido designado/a como Preceptor exitosamente                                                                                              |
            | 40400400 | Marisa      | Amuchástegui | ESPACIO_CURRICULAR | Historia          | 5    | 2      | Maniana | 2023-03-01 |            | 200    | Marisa Amuchástegui ha sido designado/a a la asignatura Historia a la división 5º 2º turno Maniana exitosamente                                             |
            | 50500500 | Raúl        | Gómez        | ESPACIO_CURRICULAR | Geografia         | 3    | 1      | Tarde   | 2023-03-01 | 2025-12-31 | 200    | Raúl Gómez ha sido designado/a a la asignatura Geografia a la división 3º 1º turno Tarde exitosamente                                                       |
            | 99100000 | Ermenegildo | Sabat        | ESPACIO_CURRICULAR | Fisica            | 2    | 3      | Maniana | 2023-03-01 |            | 200    | Ermenegildo Sabat ha sido designado/a a la asignatura Fisica a la división 2º 3º turno Maniana exitosamente                                                 |
            | 99200000 | María Rosa  | Gallo        | ESPACIO_CURRICULAR | Matematicas       | 1    | 1      | Tarde   | 2023-03-01 |            | 200    | María Rosa Gallo ha sido designado/a a la asignatura Matematicas a la división 1º 1º turno Tarde exitosamente                                               |
            | 99300000 | Homero      | Manzi        | ESPACIO_CURRICULAR | Tecnologia        | 4    | 3      | Maniana | 2023-03-01 |            | 200    | Homero Manzi ha sido designado/a a la asignatura Tecnologia a la división 4º 3º turno Maniana exitosamente                                                  |
            | 30300300 | Pedro       | Benítez      | CARGO              | Preceptor         | 0    | 0      | null    | 2023-05-01 | 2024-12-31 | 200    | Pedro Benítez NO ha sido designado/a como Preceptor pues el cargo solicitado lo ocupa Susana Álvarez para el período                                        |
            | 60600600 | Inés        | Torres       | ESPACIO_CURRICULAR | Geografia         | 3    | 1      | Tarde   | 2023-07-01 | 2023-10-15 | 200    | Inés Torres NO ha sido designado/a debido a que la asignatura Geografia de la división 3º 1º turno Tarde lo ocupa Raúl Gómez para el período                |
            | 20000000 | Rosalía     | Fernandez    | CARGO              | Auxiliar ADM      | 0    | 0      | null    | 2024-01-01 | 2024-12-31 | 200    | Rosalía Fernandez ha sido designado/a como Auxiliar ADM exitosamente                                                                                        |
            | 88888888 | Marisa      | Balaguer     | CARGO              | Preceptor         | 0    | 0      | null    | 2025-01-01 | 2025-12-31 | 200    | Marisa Balaguer ha sido designado/a como Preceptor exitosamente                                                                                             |
            | 88100000 | Raúl        | Orellanos    | CARGO              | Conserje          | 0    | 0      | null    | 2023-01-01 | 2023-12-31 | 200    | Raúl Orellanos ha sido designado/a como Conserje exitosamente                                                                                               |
            | 88200000 | Matías      | Barto        | CARGO              | Portero           | 0    | 0      | null    | 2023-01-01 | 2023-12-31 | 200    | Matías Barto ha sido designado/a como Portero exitosamente                                                                                                  |
            | 88300000 | Andrea      | Sosa         | ESPACIO_CURRICULAR | Ingles            | 2    | 3      | Maniana | 2023-01-01 | 2023-12-31 | 200    | Andrea Sosa ha sido designado/a a la asignatura Ingles a la división 2º 3º turno Maniana exitosamente                                                       |
            | 88400000 | Laura       | Barrientos   | ESPACIO_CURRICULAR | Astrofisica       | 3    | 1      | Tarde   | 2023-01-01 | 2023-12-31 | 200    | Laura Barrientos ha sido designado/a a la asignatura Astrofisica a la división 3º 1º turno Tarde exitosamente                                               |
            | 88500000 | Natalia     | Zabala       | CARGO              | Auxiliar DOC      | 0    | 0      | null    | 2023-01-01 | 2023-12-31 | 200    | Natalia Zabala ha sido designado/a como Auxiliar DOC exitosamente                                                                                           |
            | 45380520 | Lucas       | San Martin   | ESPACIO_CURRICULAR | Derecho           | 4    | 3      | Maniana | 2023-03-01 |            | 200    | Lucas San Martin ha sido designado/a a la asignatura Derecho a la división 4º 3º turno Maniana exitosamente                                                 |
            | 45380520 | Lucas       | San Martin   | ESPACIO_CURRICULAR | Geografia         | 3    | 1      | Tarde   | 2023-06-30 | 2024-12-28 | 200    | Lucas San Martin NO ha sido designado/a debido a que la asignatura Geografia de la división 3º 1º turno Tarde lo ocupa Raúl Gómez para el período           |
            | 45380520 | Lucas       | San Martin   | ESPACIO_CURRICULAR | Ingles            | 2    | 3      | Maniana | 2024-02-22 | 2024-12-31 | 200    | Lucas San Martin ha sido designado/a a la asignatura Ingles a la división 2º 3º turno Maniana exitosamente                                                  |
            | 45380520 | Lucas       | San Martin   | ESPACIO_CURRICULAR | Informática       | 1    | 1      | Tarde   | 2023-03-01 |            | 200    | Lucas San Martin ha sido designado/a a la asignatura Informática a la división 1º 1º turno Tarde exitosamente                                               |
            | 45380520 | Lucas       | San Martin   | ESPACIO_CURRICULAR | Teatro            | 1    | 1      | Tarde   | 2023-03-01 |            | 200    | Lucas San Martin ha sido designado/a a la asignatura Teatro a la división 1º 1º turno Tarde exitosamente                                                    |
            | 45380520 | Lucas       | San Martin   | ESPACIO_CURRICULAR | Historia          | 5    | 2      | Maniana | 2023-03-10 | 2023-08-12 | 200    | Lucas San Martin NO ha sido designado/a debido a que la asignatura Historia de la división 5º 2º turno Maniana lo ocupa Marisa Amuchástegui para el período |
            | 45682000 | Facundo     | Español      | ESPACIO_CURRICULAR | Literatura        | 1    | 1      | Tarde   | 2024-02-27 |            | 200    | Facundo Español ha sido designado/a a la asignatura Literatura a la división 1º 1º turno Tarde exitosamente                                                 |
            | 45682000 | Facundo     | Español      | ESPACIO_CURRICULAR | Frances           | 1    | 1      | Tarde   | 2024-03-04 |            | 200    | Facundo Español ha sido designado/a a la asignatura Frances a la división 1º 1º turno Tarde exitosamente                                                    |
            | 45682000 | Facundo     | Español      | ESPACIO_CURRICULAR | Química           | 1    | 1      | Tarde   | 2024-02-05 |            | 200    | Facundo Español ha sido designado/a a la asignatura Química a la división 1º 1º turno Tarde exitosamente                                                    |
            | 45682000 | Facundo     | Español      | ESPACIO_CURRICULAR | Derecho           | 4    | 3      | Maniana | 2023-03-10 | 2023-10-10 | 200    | Facundo Español NO ha sido designado/a debido a que la asignatura Derecho de la división 4º 3º turno Maniana lo ocupa Lucas San Martin para el período      |
            | 42033100 | Romina      | Lopez        | ESPACIO_CURRICULAR | Biología          | 1    | 1      | Tarde   | 2024-02-24 | 2024-12-23 | 200    | Romina Lopez ha sido designado/a a la asignatura Biología a la división 1º 1º turno Tarde exitosamente                                                      |
            | 42033100 | Romina      | Lopez        | ESPACIO_CURRICULAR | Música            | 1    | 1      | Tarde   | 2024-03-03 | 2024-12-22 | 200    | Romina Lopez ha sido designado/a a la asignatura Música a la división 1º 1º turno Tarde exitosamente                                                        |
            | 43987413 | Lautaro     | Martinez     | ESPACIO_CURRICULAR | Artes Plásticas   | 1    | 1      | Tarde   | 2024-02-16 |            | 200    | Lautaro Martinez ha sido designado/a a la asignatura Artes Plásticas a la división 1º 1º turno Tarde exitosamente                                           |
            | 43987413 | Lautaro     | Martinez     | ESPACIO_CURRICULAR | Filosofía         | 1    | 1      | Tarde   | 2024-03-02 | 2024-11-30 | 200    | Lautaro Martinez ha sido designado/a a la asignatura Filosofía a la división 1º 1º turno Tarde exitosamente                                                 |
            | 40112000 | Francisco   | Gomez        | ESPACIO_CURRICULAR | Educación Física  | 3    | 2      | Maniana | 2024-06-10 |            | 200    | Francisco Gomez ha sido designado/a a la asignatura Educación Física a la división 1º 2º turno Maniana exitosamente                                         |
            | 40987654 | Julia       | Martinez     | ESPACIO_CURRICULAR | Ética             | 2    | 3      | Tarde   | 2024-05-20 |            | 200    | Julia Martinez ha sido designado/a a la asignatura Ética a la división 1º 2º turno Maniana exitosamente                                                       |
            | 43322112 | Marcos      | Perez        | ESPACIO_CURRICULAR | Sociología        | 4    | 1      | Maniana | 2024-06-05 |            | 200    | Marcos Perez ha sido designado/a a la asignatura Sociología a la división 1º 2º turno Maniana exitosamente                                                  |