"""Creación de la tabla Lote

Revision ID: e152c31dc84f
Revises: 
Create Date: 2024-10-09 13:45:46.377369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e152c31dc84f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_calle', sa.String(length=50), nullable=True),
    sa.Column('nombre_calle', sa.String(length=100), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('manzana', sa.String(length=10), nullable=True),
    sa.Column('lote', sa.String(length=10), nullable=True),
    sa.Column('piso', sa.String(length=10), nullable=True),
    sa.Column('departamento', sa.String(length=10), nullable=True),
    sa.Column('entre_calles_1', sa.String(length=100), nullable=True),
    sa.Column('entre_calles_2', sa.String(length=100), nullable=True),
    sa.Column('distancia_esquinas', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lote')
    # ### end Alembic commands ###
